#!/usr/bin/env bash

export PATH=$HOME/scripts:$HOME/.local/bin:/usr/local/bin:$HOME/bin:$PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export EDITOR='vim' ALTERNATE_EDITOR='vim' VISUAL='vim' BUNDLER_EDITOR='atom'
export force_color_prompt=true

# Bash History
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
export HISTIGNORE='&:clear:ls:cd:[bf]g:exit:[ t\]*'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# Bitbake Env settings
# export BBPATH=/stuff/maemo-angstrom:/stuff/build:/stuff/openembedded
# export PATH=/stuff/bitbake/bin:$PATH

# Proxy settings
#export http_proxy='127.0.0.1:5050'
#export https_proxy='127.0.0.1:5050'
#export ftp_proxy='127.0.0.1:5050'
